#!/usr/bin/env python3
"""Validate application artwork is bundled, local-first, and distributable-safe."""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
IMAGE_RE = re.compile(r'''(?:src|href)=['"]([^'"]+)['"]|url\(['"]?([^)'"]+)['"]?\)''')
REMOTE_RE = re.compile(r'^https?://', re.I)
DATA_RE = re.compile(r'^(data:|#|mailto:|javascript:)', re.I)
BUILD_FILES = json.loads((ROOT/'package.json').read_text()).get('build',{}).get('files',[])
PLACEHOLDER_OK = ('assets/placeholders/',)

errors=[]; warnings=[]; local=[]; remote=[]; missing=[]; placeholders=[]

def exact_exists(rel):
    if not rel or REMOTE_RE.match(rel) or DATA_RE.match(rel): return True
    p=Path(rel)
    if p.is_absolute() or '..' in p.parts:
        errors.append(f'Path points outside application: {rel}'); return False
    cur=ROOT
    for part in p.parts:
        names={x.name for x in cur.iterdir()} if cur.exists() else set()
        if part not in names:
            return False
        cur=cur/part
    return cur.is_file()

def in_zip(rel):
    if rel.startswith('assets/'): return True
    if '/' not in rel and rel.endswith('.png'): return True
    return rel in BUILD_FILES

def note(ref, source, required=True):
    if REMOTE_RE.match(ref):
        remote.append((source,ref));
        if required: errors.append(f'Important image depends only on internet: {source} -> {ref}')
        return
    if DATA_RE.match(ref): return
    local.append((source,ref))
    if 'assets/placeholders/' in ref: placeholders.append((source,ref))
    if not exact_exists(ref): missing.append((source,ref)); errors.append(f'Missing local image or capitalization mismatch: {source} -> {ref}')
    elif not in_zip(ref): errors.append(f'Local image is not included in Windows ZIP: {source} -> {ref}')

# item-images: assetPath is required; imageUrl may exist only as non-required metadata/fallback.
data=json.loads((ROOT/'assets/item-images.json').read_text())
for cat in ['primary','sidearm','throwable','stratagem','booster']:
    for i,e in enumerate(data.get(cat,[]),1):
        name=e.get('name') or f'#{i}'
        ap=(e.get('assetPath') or '').strip(); iu=(e.get('imageUrl') or '').strip()
        if not ap: errors.append(f'{cat} {name} has no local assetPath')
        else: note(ap, f'assets/item-images.json:{cat}:{name}')
        if iu: remote.append((f'assets/item-images.json:{cat}:{name}:imageUrl',iu))

# index static refs and WARBOND_ART values.
text=(ROOT/'index.html').read_text()
for m in IMAGE_RE.finditer(text):
    ref=(m.group(1) or m.group(2) or '').strip()
    if not ref or ref.startswith('http') and 'youtube.com' in ref: continue
    if re.search(r'\$\{|<|>|`|\s', ref): continue
    if ref.endswith('.js'): continue
    if re.search(r'\.(png|jpe?g|gif|webp|svg|ico)$', ref, re.I): note(ref, 'index.html')
for key,val in re.findall(r'"([^"]+)":\s*"([^"]+\.(?:svg|png|jpg|jpeg|webp))"', text):
    if val.startswith('assets/') or val.endswith(('.png','.svg')): note(val, f'index.html:{key}')

report=ROOT/'assets'/'ARTWORK_AUDIT.md'
def section(title, rows):
    if not rows:
        return f'## {title}\n\nNone.\n\n'
    body = '\n'.join(f'- `{src}` -> `{ref}`' for src, ref in sorted(set(rows)))
    return f'## {title}\n\n{body}\n\n'

report.write_text('# Artwork audit\n\n'
 'Generated by `python scripts/validate_assets.py`. Remote `imageUrl` fields are retained as source metadata/fallback only; every required item visual has a bundled `assetPath`.\n\n'
 f'## Counts\n\n- Local pictures: {len(local)}\n- Remote pictures/source URLs: {len(remote)}\n- Missing pictures: {len(missing)}\n- Existing placeholders: {len(placeholders)}\n\n'
 '## Placeholder behavior\n\nMissing or unverified item artwork uses clearly marked SVG files under `assets/placeholders/`. Warbond groups without approved cover artwork use `assets/placeholders/warbond/warbond-placeholder.svg`. Runtime image handlers prefer local `assetPath` values and fall back to inline `N/A` text only if a bundled asset unexpectedly fails.\n\n'
 + section('Local pictures', local)
 + section('Remote pictures/source URLs', remote)
 + section('Missing pictures', missing)
 + section('Existing placeholders', placeholders))

if errors:
    print('❌ Asset validation failed:'); [print(' - '+e) for e in errors]; sys.exit(1)
print('✅ Asset validation passed')
print(f'Local pictures: {len(local)}; remote metadata/fallback URLs: {len(remote)}; missing: {len(missing)}; placeholders: {len(placeholders)}')
